""" Relevant constants and enum classes for the decisionmaking subpackage """

from enum import Enum

NUMBER_OF_SECONDS_BETWEEN_ROUTINE_CHECKS = 0.05
NUMBER_OF_SECONDS_BETWEEN_ROTATION_CHECKS = 0.05
NUMBER_OF_SECONDS_BETWEEN_SIGNAL_SAMPLES = 0.10

POSITION_SUDDEN_CHANGE_THRESHOLD = 5
HEADING_SUDDEN_CHANGE_THRESHOLD = 20


class TranslationStrategyType(Enum):
    BASIC_WHEEL_SERVOING = "TRANSLATION_BASIC_SERVOING"
    TRUST_MATERIAL_SERVOING = "TRANSLATION_TRUSTING"


class RotationStrategyType(Enum):
    BASIC_WHEEL_SERVOING = "ROTATION_BASIC_SERVOING"
    TRUST_MATERIAL_SERVOING = "ROTATION_TRUSTING"


class Step(Enum):

    STANBY = 0
    ROTATE_TO_STANDARD_HEADING = 1
    PREPARE_TRAVEL_TO_ANTENNA_ZONE = 2
    TRAVEL_TO_ANTENNA_ZONE = 3
    PREPARE_SEARCH_FOR_ANTENNA = 4
    SEARCH_FOR_ANTENNA = 5
    PREPARE_MOVING_TO_ANTENNA_POSITION = 6
    MOVING_TO_ANTENNA_POSITION = 7
    ACQUIRE_INFORMATION_FROM_ANTENNA = 8
    PREPARE_MOVING_TO_OFFSET = 9
    MOVE_TO_OFFSET = 10
    PREPARE_MARKING_ANTENNA_POSITION = 11
    MARKING_ANTENNA_POSITION = 12
    COMPUTE_PAINTINGS_AREA = 13
    TRAVEL_TO_PAINTINGS_AREA = 14
    PREPARE_ALIGN_WITH_CAPTURE = 15
    ALIGN_WITH_CAPTURE = 16
    PREPARE_CAPTURE_OF_PAINTING = 17
    ROTATE_TO_FACE_PAINTING = 18
    CAPTURE_CORRECT_PAINTING = 19
    ROTATE_BACK_AFTER_CAPTURE = 20
    PREPARE_TRAVEL_TO_DRAWING_ZONE = 21
    TRAVEL_TO_DRAWING_ZONE = 22
    PREPARE_REALIGN_WITH_FIRST_VERTEX_DRAWN = 23
    REALIGN_WITH_FIRST_VERTEX_DRAWN = 24
    PREPARE_TO_DRAW = 25
    DRAWING = 26
    PREPARE_EXIT_OF_DRAWING_ZONE = 27
    EXITING_DRAWING_ZONE = 28
    TERMINATE_SEQUENCE = 29
    REPOSITION_FOR_CAPTURE_RETRY = 50


def next_step(current_step):

    try:
        step_to_return = Step(current_step.value + 1)
    except ValueError:
        return Step.STANBY

    return step_to_return
