# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1101, 648)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.central_widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chrono_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chrono_label.sizePolicy().hasHeightForWidth())
        self.chrono_label.setSizePolicy(sizePolicy)
        self.chrono_label.setMinimumSize(QtCore.QSize(100, 20))
        self.chrono_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.chrono_label.setTextFormat(QtCore.Qt.AutoText)
        self.chrono_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.chrono_label.setIndent(0)
        self.chrono_label.setObjectName("chrono_label")
        self.verticalLayout.addWidget(self.chrono_label)
        self.chrono_lcd = QtWidgets.QLCDNumber(self.layoutWidget)
        self.chrono_lcd.setObjectName("chrono_lcd")
        self.verticalLayout.addWidget(self.chrono_lcd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_2.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout_2.addWidget(self.stop_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.game_progress_bar = QtWidgets.QProgressBar(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_progress_bar.sizePolicy().hasHeightForWidth())
        self.game_progress_bar.setSizePolicy(sizePolicy)
        self.game_progress_bar.setMinimumSize(QtCore.QSize(400, 20))
        self.game_progress_bar.setBaseSize(QtCore.QSize(0, 20))
        self.game_progress_bar.setProperty("value", 0)
        self.game_progress_bar.setObjectName("game_progress_bar")
        self.horizontalLayout.addWidget(self.game_progress_bar)
        self.tab_widget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab_widget.setFont(font)
        self.tab_widget.setAutoFillBackground(False)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(True)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.test_tab_widget = QtWidgets.QWidget()
        self.test_tab_widget.setObjectName("test_tab_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.test_tab_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.list_view_test = QtWidgets.QListView(self.test_tab_widget)
        self.list_view_test.setObjectName("list_view_test")
        self.gridLayout.addWidget(self.list_view_test, 0, 0, 1, 1)
        self.tab_widget.addTab(self.test_tab_widget, "")
        self.world_tab = QtWidgets.QWidget()
        self.world_tab.setObjectName("world_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.world_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.world_view = QtWidgets.QGraphicsView(self.world_tab)
        self.world_view.setObjectName("world_view")
        self.gridLayout_2.addWidget(self.world_view, 0, 0, 1, 1)
        self.tab_widget.addTab(self.world_tab, "")
        self.position_tab = QtWidgets.QWidget()
        self.position_tab.setObjectName("position_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.position_tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.position_view = QtWidgets.QGraphicsView(self.position_tab)
        self.position_view.setObjectName("position_view")
        self.gridLayout_3.addWidget(self.position_view, 0, 0, 1, 1)
        self.tab_widget.addTab(self.position_tab, "")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        main_window.setCentralWidget(self.central_widget)
        self.main_menu_bar = QtWidgets.QMenuBar(main_window)
        self.main_menu_bar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.main_menu_bar.setObjectName("main_menu_bar")
        self.main_menu = QtWidgets.QMenu(self.main_menu_bar)
        self.main_menu.setObjectName("main_menu")
        main_window.setMenuBar(self.main_menu_bar)
        self.close_menu_item = QtWidgets.QAction(main_window)
        self.close_menu_item.setObjectName("close_menu_item")
        self.main_menu.addAction(self.close_menu_item)
        self.main_menu_bar.addAction(self.main_menu.menuAction())

        self.retranslateUi(main_window)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.chrono_label.setText(_translate("main_window", "Chronograph"))
        self.start_btn.setText(_translate("main_window", "Start"))
        self.stop_btn.setText(_translate("main_window", "Stop"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.test_tab_widget), _translate("main_window", "test_Tab"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.world_tab), _translate("main_window", "WorldView"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.position_tab), _translate("main_window", "Position du robot"))
        self.main_menu.setTitle(_translate("main_window", "Menu"))
        self.close_menu_item.setText(_translate("main_window", "Fermer"))

