# These were taken from the image samples
PAINTING_FRAME_LOWER_GREEN = (35.1, 108, 49.5)
PAINTING_FRAME_UPPER_GREEN = (78.1, 255, 236.5)

# The dimension of the warped images (chosen arbitrarily)
WARPED_IMAGE_DIMENSIONS = (300, 300)
WARPED_IMAGE_CORNERS = [[0, 0], [300, 0], [300, 300], [0, 300]]

# The real dimensions in centimeters
REAL_PAINTING_DIMENSION = 14.8
REAL_DRAWING_AREA_DIMENSION = 59.7

#: The ratios between the real painting frame dimension and the image's one
PAINTING_DIMENSION_RATIO = REAL_PAINTING_DIMENSION / WARPED_IMAGE_DIMENSIONS[0]

LOWER_TRIANGLE_BOX_SIZE = 28
HIGHER_TRIANGLE_BOX_SIZE = 80

# drawing zone borders : green range
MIN_GREEN = [40, 80, 120]
MAX_GREEN = [80, 255, 255]

MIN_MAGENTA = [160, 100, 100]
MAX_MAGENTA = [170, 255, 255]

DRAWING_ZONE_MIN_AREA = 100000
DRAWING_ZONE_MAX_AREA = 300000

OBSTACLE_MIN_RADIUS = 20
OBSTACLE_MAX_RADIUS = 60
OBSTACLES_WHITE_CIRCLE_MIN_RADIUS = 30

MIN_ROBOT_CIRCLE_RADIUS = 5
MIN_DISTANCE_BETWEEN_ROBOT_TOP_CIRCLES = 60

LEFT_GAP_FROM_DRAWING_ZONE = 25.5  # in cm
RIGHT_GAP_FROM_DRAWING_ZONE = 145
TOP_GAP_FROM_DRAWING_ZONE = 25.75
BOTTOM_GAP_FROM_DRAWING_ZONE = 25.75
DRAWING_ZONE_WORLD_ARC_LENGTH = 59.7

MAXIMUM_DISTANCE_BETWEEN_SIMILAR_COORDINATES = 10
MAXIMUM_ANGLE_BETWEEN_SIMILAR_ANGLES = 5

ROBOT_TRIANGLE_MINIMAL_AREA = 1600
ROBOT_TRIANGLE_MAXIMAL_AREA = 1800

NUMBER_OF_CAPTURES_TO_COMPARE = 10

OBSTACLES_HEIGHT = 0
ROBOT_HEIGHT = 0

TABLE_WIDTH = 230
TABLE_HEIGHT = 112
